### ISSUE TITLE
Make sure to ignore channels in local configuration

### ISSUE THREAD

**Issue by drdavella** [tox-dev/tox-conda#10]
Originally at https://github.com/drdavella/tox-conda/issues/1.

**Comment by pylang** [comment]
Let me begin by saying this is a long awaited, wonderful plugin!

My tox env that once installed the entire scipy stack from pip took 5+ mins.  With this plugin - 30+ secs!  Thank you so much.

*Observation*

I ran into an error re-running tox on Windows.  The first time it seems to run alright.  The second or third time I get an unusually `PermissionError` when conda tries to install `vs2015_runtime-...`.

I imagine this can be reproduced running tox with the following dependencies several times.

```
conda_deps=

    ipykernel
    numpy
    scipy
    pandas
    sympy
```

I can alleviate this error temporarily by deleting the tox env, but of course this is not preferable.  Thanks again!

**Comment by drdavella** [comment]
Hi @pylang thanks for the feedback! I have opened a new issue to track the problem you reported. Please see #19 for discussion.

**Comment by AntoineD** [comment]
Not sure what the issue was, closing for now.
