### ISSUE TITLE
Add support for Python 3.10

### ISSUE THREAD

**Issue by JulienGrv** [tox-dev/tox-conda#105]
The current regex cannot parse py310 correctly, resulting in python=3.1.0 instead of python=3.10

**Comment by JulianOrteil** [comment]
Also encountering this. Trying py3.10 (like py2.7) installs python 3.9??

**Comment by chrisjsewell** [comment]
Thanks for the fix, sorry for being impatient, but would be nice to get this in a release 😉

**Comment by AntoineD** [comment]
@chrisjsewell The new version 0.8.4 is available now.

**Comment by chrisjsewell** [comment]
yep that all works now, thanks!
