### ISSUE TITLE
Consider making conda a dependency

### ISSUE THREAD

**Issue by drdavella** [tox-dev/tox-conda#11]
Originally at https://github.com/drdavella/tox-conda/issues/2.

**Comment by pylang** [comment]
I'm curious about the rationale here.

**Comment by AntoineD** [comment]
@drdavella could you elaborate a bit more please?

**Comment by drdavella** [comment]
Hi! Sorry for the lack of detail here. I can't quite remember but I think the idea was to make `pip install tox-conda` also install `conda`. But I'd be fine with closing this ticket.
