### ISSUE TITLE
how to specify conda install 

### ISSUE THREAD

**Issue by oguitart** [tox-dev/tox-conda#12]
Hi,
let's say I need to install the following package byy:

conda install -y -c rdkit rdkit
conda install -y -c openbabel openbabel

How I should write this in the tox.ini? I should put in the conda_deps section like that?:
conda_deps=
    rdkit
    openbabel

thanks,

oriol

**Comment by obestwalter** [comment]
Hi @oguitart  where you able to figure it out? Please keep in mind that this plugin is still in its early stages so actual feedback what is needed and what could be improved would be appreciated.

**Comment by oguitart** [comment]
Yes, I finally understood that by using conda_deps and conda_channels. I could do the same thing. Now it works perfect.
Thanks
