### ISSUE TITLE
Python 3.10 test env

### ISSUE THREAD

**Issue by moux233** [tox-dev/tox-conda#123]
Hello and thank you for maintaining tox-conda.
I cannot get tox-conda to create a python 3.10. It tries to create a python 3.1 env instead.

I get the following error :
ERROR: FAIL could not package project - v = InvocationError("'C:\\Users\\maxime_rattier\\Miniconda3\\Scripts\\conda.exe' create --yes -p 'C:\\Users\\maxime_rattier\\Documents\\10.Sources\\umixapi\\.tox\\py310-test' python=3.1", 1)

From what I understand the get_py_version function in the plugin.py module has a regular expression which does not support two-digits python minor version.
I am not familiar enough with regex to propose a patch.

**Comment by AntoineD** [comment]
There has been a [fix](https://github.com/tox-dev/tox-conda/commit/978da65bc74f4613c140ff277c52563cd17149a8) for this some months ago, which version of tox-conda are you using?

**Comment by moux233** [comment]
Sorry you are right I got stuck with an older version.

**Comment by moux233** [comment]
Closing.
