### ISSUE TITLE
Memory management issue with newer versions of conda/mamba

### ISSUE THREAD

**Issue by Zeitsperre** [tox-dev/tox-conda#152]
I've been running into issues with newer versions of conda/mamba. Behaviour suggests that managing an environment via tox-conda is causing a memory management issue (SIGINT errors on GitHub Actions, crashes locally).

Here's one such example: https://github.com/Ouranosinc/xclim/actions/runs/3623121664/jobs/6108641201#step:7:13

Very difficult to know what's going on internally. Absolutely no issues when creating/updating env manually. Anything I can do to find out more on my end?

**Comment by AntoineD** [comment]
How could I reproduce this locally?

**Comment by Zeitsperre** [comment]
Thanks for the speedy response! Running from an env with conda/mamba enabled:
```
$ mamba update -n base --all
$ git clone git@github.com:Ouranosinc/xclim.git
$ cd xclim
$ mamba install tox-conda
$ tox -e opt-slow-mamba
```
The memory issue should become apparent not long after that.

**Comment by AntoineD** [comment]
I've just tested on fedora 36: no crash either.
