### ISSUE TITLE
tox envs in `conda list`

### ISSUE THREAD

**Issue by pylang** [tox-dev/tox-conda#23]
On my isolated machine running `tox-conda`, I find my tox envs under:

    > conda env list

I did not expect tox envs in that list, though I can reason why they might be there.  I'm not sure if this is caused by a newer tox version, but I noticed post installation of this plugin.  Can someone confirm:

1. after running a tox env with tox-conda
1. invoke `> conda env list`
1. see if tox envs are listed among conda envs

Thanks.

**Comment by aperezhortal** [comment]
I also see the tox envs in `conda env list`. Is this an expected behavior in tox-conda? 
Thanks

**Comment by AntoineD** [comment]
That's the expected behavior.
