### ISSUE TITLE
Environment is not properly activated on Windows and MacOS.

### ISSUE THREAD

**Issue by tobiasraabe** [tox-dev/tox-conda#24]
Hi,

first, of all, thanks for the package 👍. I was using tox before, but only with this package it became much more convenient for data science projects.

But, I ran into an issue where I cannot pin down exactly where the error is.

1. Long time ago, we noticed that our tests on Windows failed on Travis with Python 3.7.. NumPy seems to be missing and we attributed the error to a faulty conda package. As we could not pin down the error, we deactivated the tests on python 3.7. Python 3.6 was fine.
2. Now, without any apparent reason, the tests on MacOS on Azure fail for both, Python 3.6 and 3.7. https://dev.azure.com/opensourceeconomics/respy/_build/results?buildId=65. Same error as before with Python 3.7.
3. Now, I did some more testing on my Windows machine and these are the results:
  - If I activate the environment created under .tox/pytest manually and run the tests, everything is fine.
  - If I run ``tox -e pytest`` in a clean environment without NumPy installed, the tests will fail because NumPy is missing.
  - If I run ``tox -e pytest`` in an environment where NumPy is installed, everything is fine.

Thus, I suspect that the environment is not properly activated and parts of the environment which is activated while running ``tox -e pytest`` mix with the test environment.

I know this is not much information and I am not actually sure this error is on ``tox-conda``'s side, but maybe you can give me some advice on how to get more information.

**Comment by tobiasraabe** [comment]
I think the error is more related to issues with conda, Python, NumPy and Windows where DLLs might not be found.

**Comment by obestwalter** [comment]
Hey @tobiasraabe thanks for giving an update about that. I will have the opportunity to battle test this plug-in with a group of Windows users next week so it's good to know that basically it should work. Any extra information that you could provide about your particular problem would be very appreciated!

**Comment by tobiasraabe** [comment]
Thanks for coming back to me :). Now, I have a small hopefully reproducible example for you.

1. Create a new environment with ``conda create -n tc python=3.7 tox-conda -c defaults -c conda-forge`` and activate it with ``conda activate tc``.
2. Use this ``tox.ini``:
    ````
    [tox]
    envlist = python
    skipsdist = True
    skip_missing_interpreters = True

    [testenv]
    basepython = python

    [testenv:python]
    conda_channels =
        defaults
    conda_deps =
        numpy
    commands =
        python -c "import numpy as np"
    ````
3. Run ``tox`` which resuslts in an error. Something like this
    ````
    (tc) PS C:\Users\tobia\Desktop\tox-conda> tox
    python create: C:\Users\tobia\Desktop\tox-conda\.tox\python
    python installcondadeps: numpy
    python installed: certifi==2019.6.16,mkl-fft==1.0.12,mkl-random==1.0.2,numpy==1.16.4,wincertstore==0.2
    python run-test-pre: PYTHONHASHSEED='345'
    python run-test: commands[0] | python -c 'import numpy as np'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\tobia\Desktop\tox-conda\.tox\python\lib\site-packages\numpy\__init__.py", line 140, in <module>
        from . import _distributor_init
      File "C:\Users\tobia\Desktop\tox-conda\.tox\python\lib\site-packages\numpy\_distributor_init.py", line 34, in <module>
        from . import _mklinit
    ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.
    ````
4. Install ``numpy`` in ``tc`` with ``conda install numpy``.
5. Run the tests again with ``tox``. Now, you get
    ````
    (tc) PS C:\Users\tobia\Desktop\tox-conda> tox
    python recreate: C:\Users\tobia\Desktop\tox-conda\.tox\python
    python installcondadeps: numpy
    python installed: certifi==2019.6.16,mkl-fft==1.0.12,mkl-random==1.0.2,numpy==1.16.4,wincertstore==0.2
    python run-test-pre: PYTHONHASHSEED='66'
    python run-test: commands[0] | python -c 'import numpy as np'
    ______________________________________________________ summary _______________________________________________________
      python: commands succeeded
      congratulations :)
    ````

I have not tested it for Python 3.6, but that should also raise an error.

**Comment by obestwalter** [comment]
Thanks!

**Comment by adament** [comment]
I ran into this problem for another compiled extension, it seems that environment_root\Library\bin is not put into PATH. Which at least seems to be the cause of my problem. This is also consistent with numpy failing to import _mklinit in the example from @tobiasraabe. Since the mkl dlls are also in Library\bin.

**Comment by tobiasraabe** [comment]
I found a solution to my problems on Azure Pipelines.

On Windows, I had to add ``CONDA_DLL_SEARCH_MODIFICATION_ENABLE = 1`` to the tox.ini under setenv.

On MacOS, I had to clean the conda package index with ``conda clean -i``.

**Comment by QuLogic** [comment]
I don't think this is platform-specific; it's just more obvious on some of them depending on what things you have installed globally.
