### ISSUE TITLE
Env is always recreated on windows with some conda deps

### ISSUE THREAD

**Issue by rompom** [tox-dev/tox-conda#27]
Tox version : 3.13.2
tox-conda : 0.3.0

When first creating a virtual env, Tox create a file called **.tox-config1** with ,among other things, list the dependencies used ( [see here]( https://github.com/tox-dev/tox/blob/master/src/tox/venv.py#L298) )

When running tox again, he check this file ( [see here](https://github.com/tox-dev/tox/blob/master/src/tox/venv.py#L229) ) and the current list of depencies, and if there is a mismatch, Tox reinstall the virtual env.

Now the issue is that tox-conda remove the conda dependencies ( [see here](https://github.com/tox-dev/tox-conda/blob/master/tox_conda/plugin.py#L156) ) before running the pip install (which is ok), but doesn't re-inject them after the installations.

So when Tox write the config file, he doesn't have them, but when run a second time, they are present => config is different, env is rebuilt.

**Comment by janLuke** [comment]
The fix doesn't seem to work for me. Tox keeps recreating all the environments that require a version of Python different from the one I have installed in my root environment. Maybe I am missing some fundamental obvious step (?)

**Comment by AntoineD** [comment]
There is a fix in the master branch for this, could you give it a try?

**Comment by AntoineD** [comment]
No update from author: closing.
