### ISSUE TITLE
Support Python 3.7

### ISSUE THREAD

**Issue by mydpy** [tox-dev/tox-conda#32]
We're starting to move our Python projects to 3.7+. Lack of support for 3.7+ will prevent us from using `tox-conda` for test automation.

**Comment by asford** [comment]
I'm using tox-conda for python 3.7 tests without any issues. The standard `py37` env definition and `base_python=python3.7` clauses in `tox.ini` appear to work file.

**Comment by mydpy** [comment]
This issue can be closed. I was able to configure this working properly with Python 3.7. Thank you.
