### ISSUE TITLE
tox-conda interacts badly with numpy on Windows, Python 3.7/3.8

### ISSUE THREAD

**Issue by goerz** [tox-dev/tox-conda#37]
Having `numpy` in `conda_deps` on Windows with Python 3.7 or Python 3.8 causes a crash when any command inside the environment tries to import `numpy`. Python 3.6 works.

See cross-reference https://github.com/numpy/numpy/issues/15537

**Comment by goerz** [comment]
Also https://github.com/conda-forge/numpy-feedstock/issues/184

**Comment by goerz** [comment]
It seems the issue may be that `numpy` does not load unless the conda environment is explicitly activated (see https://github.com/numpy/numpy/issues/15537#issuecomment-583773970). Does `tox-conda` activate the environments that it manages (or mimick *exactly* what `conda activate <envname>` would do)?

**Comment by Choc13** [comment]
I believe we are also seeing this issue, however we are seeing it in a tox environment that has `basepython=python3.6`.

**Comment by tlambert03** [comment]
I think I might be seeing this as well (though for me it fails on 3.6 as well).  Same setup as @goerz mentioned, numpy gets installed via `conda_deps`.  Only fails on windows.  In case it's an important detail, I'm on github actions, using goanpeca/setup-miniconda@v1.6.0 to install conda.  Here's a failing test: https://github.com/tlambert03/napari-omero/runs/804849289?check_suite_focus=true#step:6:62

**Comment by Choc13** [comment]
I have managed to find a work around for this. By setting `CONDA_DLL_SEARCH_MODIFICATION_ENABLE = 1` in the `setenv` section of the tox testenv configuration it works again. There is more information in the [conda docs](https://docs.conda.io/projects/conda/en/latest/user-guide/troubleshooting.html#numpy-mkl-library-load-failed) about this workaround.

**Comment by rwhitt2049** [comment]
A detail about @Choc13 's DLL env variable fix. I've noticed this only works with numpy from the default channel from anaconda.com. It does not however, seem to work if you install numpy from conda-forge.

**Comment by basnijholt** [comment]
@rwhitt2049, I can indeed confirm that if *does not* work with NumPy installed from `conda-forge`.

I still see this issue for NumPy v1.20.1.

Did you manage to find a workaround?

**Comment by basnijholt** [comment]
I managed to work around it by commenting out the 
```
conda_channels =
  conda-forge
```
section.

Unfortunately, this led to some other issues, like [this](https://stackoverflow.com/questions/57484399/issue-importing-scikit-learn-module-scipy-has-no-attribute-lib). In the end I had to install both `numpy`, `scipy`, and `h5py` from the defaults channel to make it work.

I am looking forward to a better (more stable) solution!

**Comment by rwhitt2049** [comment]
@basnijholt, I got around it by setting my conda channels as follows:

```
conda_channels=
    defaults
    conda-forge
```
... and then adding an env variable as per Choc13's comment above:

```
setenv = CONDA_DLL_SEARCH_MODIFICATION_ENABLE=1
```

I have dependencies on conda-forge as well, which is why it's still in my conda_channels list. So functionally this will pull dependencies from defaults first, and then check conda-forge if it can't find the package there.

Setting the env variable took care of my dll issues.

**Comment by AntoineD** [comment]
No update from author: closing.
