### ISSUE TITLE
Request for collaboration

### ISSUE THREAD

**Issue by drdavella** [tox-dev/tox-conda#4]
I have developed an independent implementation of [tox-conda](https://github.com/drdavella/tox-conda). It has been released on [pypi](https://pypi.org/project/tox-conda/) and is currently being used in production by [sunpy](https://sunpy.org/) and [asdf](https://github.com/spacetelescope/asdf). It is under consideration for adoption by [astropy](http://www.astropy.org/) as well.

I am hoping that you might be interested in bringing this package under `tox-dev`. It would certainly benefit from increased collaboration, and I think that there are a few changes that could be made to `tox` itself in order to better support this plugin.

**Comment by obestwalter** [comment]
Hi @drdavella, oh great! Did you have a look already at the WIP implementation here? The main aim is to have some maintained and pip installable version of tox-conda. If your implementation is already working in production, that might be the one then that we should take into tox-dev (or merge the code here).

I'll be at the 35c3 after christmas and one of the things I wanted to sound out is how to get to some kind of working version of a tox-conda plugin, so good timing :tada:

**Comment by drdavella** [comment]
@obestwalter yes I did see the WIP implementation and even left some review comments a few months ago, but it seems like there hasn't been any activity there at all for quite some time.

**Comment by obestwalter** [comment]
Yes, sadly none of the tox devs seems to be using conda (including me). I tried to provide a starting point, bit did was not able to participate much in any tox related development over the last months. IIUC there were some changes needed to conda itself to make the integration work properly. I'll see if I can play around with both plugins and come up with some plan how to proceed.

**Comment by obestwalter** [comment]
@kalefranz would you have some time to chip in maybe?

**Comment by obestwalter** [comment]
Also: @TiemenSch did some work on it also (see: https://github.com/TiemenSch/tox-conda/blob/master/tox_conda/plugin.py). 

@kalefranz initial implementation is here: https://github.com/kalefranz/tox-conda/blob/initial-conda-support/tox_conda/plugin.py

Would be great if you all could put your heads together on this. It would also be nice if the main repo where the actual work is being done ends up in tox-dev for better visibility and sharing a bit of the maintenance load.

**Comment by TiemenSch** [comment]
Hi! 

Great to see some activity here! I recently started my own company, so I got rather busy and saw little time to move this forward back then. 

If I remember correctly, I got stuck on the config settings of tox. To me it was unclear which Python executable is used in what stage of the process. (You can see my confusion in the PR @drdavella reviewed https://github.com/tox-dev/tox-conda/pull/2#issuecomment-410999925). 

Should we start by merging Dan's work into this repository and start solving issues from there? 
Is the package structure compatible with what's considered regular at tox-dev?

I for one would like to merge/move, so any new user/contributor looks at what we currently consider the best effort to accomplish this. 

I propose to include some caution message at the top of the README that we're currently in a beta phase. From what I see at Dan's repo, I think especially the config option to disable tox-conda would make for 'friendly' installations https://github.com/drdavella/tox-conda/issues/11.

**Comment by obestwalter** [comment]
> Should we start by merging Dan's work into this repository and start solving issues from there?
Is the package structure compatible with what's considered regular at tox-dev?

Concentrating the work into this repo and use this as the base for releases would be preferrable. Ideally we will add the same/similar test and release automation for plugins like we have for tox, to ease maintenance and share the load. I don't know wether it is easier to merge stuff in here or move the most advanced version of the plugin into here to replace this. Please let me know which approach you prefer. The easiest and preferrable solution for me would be to keep this repo and build up from here. I am not interested to be listed as an author, so feel free to remove my name and adjust the plugin as you see fit regarding releasing also for now.

@drdavella and @TiemenSch, I invited you into the team as plugin developers into the team.
