### ISSUE TITLE
{envpython} in tox returns the wrong path to python.exe on Windows

### ISSUE THREAD

**Issue by kesmit13** [tox-dev/tox-conda#42]
Virtualenv environments put python.exe in the Scripts subdirectory of a virtual environment.  However, conda virtual environments put python.exe in the root of the virtual environment.  Since tox expects python.exe in the Scripts subdirectory, it uses that path when expanding {envpython} rather than the root.

**Comment by ktbarrett** [comment]
I am also encountering this issue.

**Comment by AntoineD** [comment]
This has been fixed in the master branch, could you guys give it a try?

**Comment by ktbarrett** [comment]
It seems to be working for me now.
