### ISSUE TITLE
Ability to configure the conda install command

### ISSUE THREAD

**Issue by pzahemszky** [tox-dev/tox-conda#46]
Similarly to how the [`install_command`](https://tox.readthedocs.io/en/latest/config.html?highlight=separator#conf-install_command) setting of test environments allows changing the default (pip) install command in tox, it would be useful to have a way of modifying the default conda install command in tox-conda (e.g. using a `conda_install_command` setting).

**Comment by Choc13** [comment]
I think this would be useful to allow people to make use of tools like `mamba`, that claim to be quicker to resolve the dependencies but have the same API as conda.

**Comment by mforbes** [comment]
Agreed.  This might also make it possible to specify an `environment.yml` file without additional sections.  See also #13 for another solution.

**Comment by AntoineD** [comment]
This feature is available in 0.7.0.

**Comment by ppoilbarbe** [comment]
I don't see it in code nor in documentation. Even on master branch the conda_exe field of environment is still fixed with "conda".
With tox, using "conda mambabuild" instead of "conda-build" takes 10 minutes (opposed to more than 24 hours) but initial filling with dependencies is still long (made with "conda install" instead of "mamba install")

**Comment by ppoilbarbe** [comment]
It does not change the main executable: conda vs mamba.

**Comment by jaystary** [comment]
I would also like to see this, as this would speed up the process of creating the environment significantly. So instead of
conda env create -n .venv -f environment.yml -> mamba env create -n .venv -f environment.yml

Thank you.

**Comment by ahgraber** [comment]
Is there any way to monkey-patch the existing code, even if it doesn't make it into tox-conda?

**Comment by corrado9999** [comment]
Digging into the code, I found out it honours the environmental variable `CONDA_EXE`, so you can run tox like this:

```sh
$ CONDA_EXE=mamba tox
```

Of course you need to install mamba in the environment running tox by yourself.

**Comment by AntoineD** [comment]
@corrado9999 Nice! I'll add this info to the README.

**Comment by AntoineD** [comment]
Closing since the README has been updated.
