### ISSUE TITLE
isolated_build breaks python version detection

### ISSUE THREAD

**Issue by saimn** [tox-dev/tox-conda#64]
When using `isolated_build = true` tox-conda will no more detect the correct version to use from the env name.

If I run something like `tox -e py37`, without `isolated_build = true`, `venv.envconfig.basepython` returns `python3.7` and [`get_py_version`](https://github.com/tox-dev/tox-conda/blob/ae3b9bbe081b30d4e338e216485a7b7286fd96de/tox_conda/plugin.py#L21) returns the correct python requirement.

But with `isolated_build = true`, the env passed to `get_py_version` / `tox_testenv_create` is the isolated (?) one, `.package`, and `get_py_version` return the Python version of my base miniconda installation (3.8):
```
(Pdb) venv.envconfig.envdir
local('/home/simon/dev/gemini/dragons/.tox/.package')
(Pdb) venv.envconfig.python_info.version_info
(3, 8, 5, 'final', 0)
(Pdb) get_py_version(venv.envconfig, action)
'python=3.8'
```

**Comment by saimn** [comment]
It seems to work, though I cannot test with the same environment, and have other (unrelated) issues with a new one.

**Comment by AntoineD** [comment]
@saimn 0.8.1 has a fix for isolated build, you may give it a try.

**Comment by AntoineD** [comment]
No update from author: closing.
