### ISSUE TITLE
Version 0.8 errors before tests can run with conda 4.8.5

### ISSUE THREAD

**Issue by mivade** [tox-dev/tox-conda#78]
Version 0.8 seems to have some serious issues which prevent me from running tests with conda 4.8.5. I get messages like the following:

```
ERROR: invocation failed (exit code 2), logfile: ...
======================================================================================================= log start ========================================================================================================
usage: conda [-h] [-V] command ...
conda: error: unrecognized arguments: --no-capture-output
```

However even if I use `tox -vv` the only place that `--no-capture-output` even shows up is in the error message. I have discovered two workarounds:

1. Downgrade to 0.7
2. Upgrade conda (with 4.10.1 this issue goes away)

To me this seems like a pretty major bug since the project readme only indicates that you need conda 4.6.0. It's also worth noting that colleagues and I have seen this same issue in CI where we were using the `continuumio/miniconda3` Docker image (the latest tag has conda version 4.9.2).

**Comment by AntoineD** [comment]
I'm sorry about that, I will fix that issue but not before sunday.

**Comment by AntoineD** [comment]
@mivade
Removing `--no-capture-output` breaks several tests of tox-conda.
The changes I proposed in tox-conda 0.8 are not perfect and this will be fixed when this plugin will be rewritten with the [release of tox 4](https://github.com/tox-dev/tox/tree/rewrite).

Meanwhile you may use your workaround and I will fix in the readme the minimum required version of conda.

The conda release note states that `--no-capture-output` was introduced in [conda 4.9.0](https://github.com/conda/conda/blob/master/CHANGELOG.md#490-2020-10-19), could you confirm that you've got the issue with the latest tag of the miniconda docker image with conda 4.9.2?

**Comment by mivade** [comment]
It does appear to work if I force pull the newest `continuumio/miniconda3` image. Maybe the issues we were experiencing was related to caching of older Docker images.

I'm happy to consider this resolved if the README gets updated (it actually currently states that `--no-capture-output` was added in 4.6.0 which appears to be incorrect).

**Comment by AntoineD** [comment]
The README has been updated.

**Comment by mivade** [comment]
Thanks!
