### ISSUE TITLE
Version 0.8 DirectoryNotACondaEnvironmentError

### ISSUE THREAD

**Issue by moux233** [tox-dev/tox-conda#80]
Hi there

I have an error with tox-conda 0.8 :
DirectoryNotACondaEnvironmentError: The target directory exists, but it is not a conda environment.
Use 'conda create' to convert the directory to a conda environment.
  target directory: G:\07.Git\qrunch\.tox\test

My env :
conda 4.10
python 3.9
tox 3.23

Workaround : downgrading to 0.7.1

Maxime

Full tox output below :

(qdev) G:\07.Git\qrunch>tox -v -e test -- -m "not slow"
using tox.ini: G:\07.Git\qrunch\tox.ini (pid 7812)
using tox-3.23.1 from c:\users\maxime_rattier\miniconda3\envs\qdev\lib\site-packages\tox\__init__.py (pid 7812)
test cannot reuse: no previous config G:\07.Git\qrunch\.tox\test\.tox-config1
test create: G:\07.Git\qrunch\.tox\test
[1924] G:\07.Git\qrunch\.tox$ 'C:\Users\maxime_rattier\Miniconda3\Scripts\conda.exe' create --yes -p test python=3.9 >log\test-0.log
test installdeps: pytest >= 2.9.1, pytest-cov, pytest-arraydiff, pytest-datadir, pytest-rerunfailures, pyqt5
[3908] G:\07.Git\qrunch$ 'G:\07.Git\qrunch\.tox\test\python.EXE' -m pip install 'pytest >= 2.9.1' pytest-cov pytest-arraydiff pytest-datadir pytest-rerunfailures pyqt5 >.tox\log\test-1.log
test wheel-make: commands[0] | pip wheel 'G:\07.Git\qrunch' --no-deps --use-pep517 --wheel-dir 'G:\07.Git\qrunch\.tox\dist'
[14580] G:\07.Git\qrunch$ 'G:\07.Git\qrunch\.tox\test\Scripts\pip.EXE' wheel . --no-deps --use-pep517 --wheel-dir '.tox\dist'
Looking in indexes: https://pypi.org/simple/
Processing g:\07.git\qrunch
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: qrunch
  Building wheel for qrunch (PEP 517) ... done
  Created wheel for qrunch: filename=qrunch-1.4.2-py3-none-any.whl size=42426778 sha256=75052acbc9142303945ea760f8db1c368ff99e10c36854e15d71c77a5f08c64e
  Stored in directory: C:\Users\maxime_rattier\AppData\Local\Temp\pip-ephem-wheel-cache-6wzsizwo\wheels\4f\c1\50\bcabd2ac2653ed12573dfafeb2bb53a84784e0b23b3b45da58
Successfully built qrunch
package .tmp\package\1\qrunch-1.4.2-py3-none-any.whl links to dist\qrunch-1.4.2-py3-none-any.whl (G:\07.Git\qrunch\.tox)
test cannot reuse: no previous config G:\07.Git\qrunch\.tox\test\.tox-config1
test create: G:\07.Git\qrunch\.tox\test
[12108] G:\07.Git\qrunch\.tox$ 'C:\Users\maxime_rattier\Miniconda3\Scripts\conda.exe' create --yes -p test python=3.9 >test\log\test-0.log
ERROR: invocation failed (exit code 1), logfile: G:\07.Git\qrunch\.tox\test\log\test-0.log
================================================= log start =================================================

DirectoryNotACondaEnvironmentError: The target directory exists, but it is not a conda environment.
Use 'conda create' to convert the directory to a conda environment.
  target directory: G:\07.Git\qrunch\.tox\test

================================================== log end ==================================================
ERROR: InvocationError for command 'C:\Users\maxime_rattier\Miniconda3\Scripts\conda.exe' create --yes -p test python=3.9 (exited with code 1)
__________________________________________________ summary __________________________________________________
ERROR:   test: InvocationError for command 'C:\Users\maxime_rattier\Miniconda3\Scripts\conda.exe' create --yes -p test python=3.9 (exited with code 1)

**Comment by moux233** [comment]
I also use tox-wheel 0.6

**Comment by AntoineD** [comment]
It may be a side effect with tox-wheel.
Could you provide the same output with tox-conda 0.7.2?

**Comment by AntoineD** [comment]
No update from author: closing.
