### ISSUE TITLE
conda run not used in subsequent tox runs

### ISSUE THREAD

**Issue by fknuth** [tox-dev/tox-conda#92]
Version 0.8 has introduced that commands are run with `conda run` which is a nice improvement. However, I realized that this only happens while the conda environment is created. On subsequent tox runs when the already created environment is used, this is not anymore the case.

I created a patch which uses the `tox_runtest_pre` hook. How can I present this patch for review? Do you work with forks or directly with feature branches in this repository?

**Comment by AntoineD** [comment]
This is not the expected behavior, all the commands shall run in a anaconda environment, this is [tested here](https://github.com/tox-dev/tox-conda/blob/master/tests/test_conda.py#L28).

Could you please explain a bit more what happens?

**Comment by fknuth** [comment]
Yes, the command execution is tested there but only while the conda environment is created and the hook for [`tox_testenv_create`](https://github.com/tox-dev/tox-conda/blob/master/tox_conda/plugin.py#L146) is executed which sets the `CondaRunWrapper`. However, when the conda environment is already created and tox reuses it in a subsequent run, `tox_testenv_create` is not executed and `CondaRunWrapper` is not set.

You can test this by executing tox twice in the linked test by adding the same lines again, namely

```python
result = cmd("-v", "-e", env_name)
result.assert_success()

for filename in ("commands_pre", "commands_post", "commands"):
    assert open(filename).read().endswith(env_name)
```

The first assertion succeeds, the second one fails then.

**Comment by AntoineD** [comment]
@fknuth Thanks for letting us know, you may give a try to the version 0.8.1 which has a fix for this.

**Comment by fknuth** [comment]
@AntoineD Thank you very much for the quick fix and release. It is working as expected now.
